# Site settings
title: Skiservis Stupava
email: strajk@me.com
description: > # this means to ignore newlines until "baseurl:"
  Skiservis Stupava
  - perfektně proškolený personál, špičkové zahraniční stroje firmy Reichmann,
  dlouholeté zkušenosti, individuální tuning lyží a snowboardů,
  servis na počkání nebo do druhého dne.
baseurl: ""
url: "http://www.skiservis-stupava.cz"